# Generated by Django 3.0.6 on 2020-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicIntro',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_URL', models.CharField(max_length=500)),
                ('music_singer', models.CharField(max_length=20)),
                ('music_time', models.CharField(max_length=20)),
                ('music_pic', models.CharField(default='https://y.gtimg.cn/mediastyle/music_v11/extra/default_300x300.jpg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_tel', models.CharField(max_length=11)),
                ('user_name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=12)),
            ],
        ),
    ]
