# Generated by Django 3.0.6 on 2020-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JEmoudel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=12)),
                ('singer', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
