# Generated by Django 3.0.6 on 2020-05-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicIntro',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_URL', models.CharField(max_length=500)),
                ('music_singer', models.CharField(max_length=20)),
                ('music_time', models.CharField(max_length=20)),
            ],
        ),
    ]
